cdklabs/aws-delivlib

README.md
package.json

Correct some stuff in `README.md`, and add some missing metadata fields in `package.json`.

chore: Address some metadata

---

lib/pipeline.ts

feat: Enable physical naming of the CodePipeline

---

README.md
lib/publishing/github/create-release.js

feat(github-releases): if changelog doesn't exist, don't fail

---

test/expected.json
test/run-test.sh

chore: Fix test expectations

---

CHANGELOG.md
package-lock.json
package.json

chore(release): 0.3.0

---

lib/pgp-secret.ts
package-lock.json
package.json
test/pgp-secret.test.ts

feat(pgp-secret): Surface parameterName attribute

---

CHANGELOG.md
package-lock.json
package.json

chore(release): 0.3.2

---

package.json
test/expected.json

chore: Correct test expectations

---

CONTRIBUTING.md
README.md
package-lock.json
package.json

Update contribution guide with information about development environment and protocol. Use standard-version for changelog management and bumps.

chore: add info about releasing new versions

---

CHANGELOG.md
package-lock.json
package.json

chore(release): 0.5.0

---

superchain/README.md

It is now referenced from the jsii contribution guide (and soon the CDK), so I want to be able to point people to this README file if they wish to install those tools themselves.

Create README for superchain

---

test/expected.json

chore: Correct broken test expectations

---

custom-resource-handlers/src/pgp-secret.ts
test/custom-resource-handlers/pgp-secret.test.ts
test/expected.json

fix: Correctly set environment before using gpg

---

superchain/Dockerfile

This is used by DocFX to analyze .NET projects.

feat(superchain): add MSBuild to Superchain image

---

lib/pipeline.ts
lib/publishing.ts
lib/publishing/s3/publish.sh
lib/shellable.ts
package-lock.json
test/pipeline.test.ts

feat: make it possible to add arbitrary processing steps

---

CHANGELOG.md
package-lock.json
package.json

chore(release): 3.1.0

---

superchain/Dockerfile

Adds ``python-wheel`` to the base image.
Closes #79 

Add python-wheel to the build environment

---

CHANGELOG.md
package-lock.json
package.json

chore(release): 3.3.0

---

README.md
lib/pipeline.ts
lib/publishing.ts
lib/publishing/pypi/publish.sh
test/expected.json
test/run-test.sh
test/test-stack.ts

This change adds a PyPI publisher to delivlib (see README).
Co-authored-by: Mitch Garnaat <garnaat@amazon.com>
Co-authored-by: Donald Stufft <dstufft@amazon.com>
---

feat: PyPI publisher

---

CHANGELOG.md
package-lock.json
package.json
superchain/Dockerfile
superchain/ssh_config

chore: Upgrade superchain/Dockerfile to latest upstream

---

superchain/Dockerfile

fix stale version in superchain

---

package-lock.json
package.json

Also fixes the transitive dependency on a vulnerable version of
handlebars (from nodenuit)

chore: Upgrade dependencies

---

.dependabot/config.yml

chore: configure dependabot

---

.dependabot/config.yml

chore: fix typo in dependabot config

---

lib/publishing.ts
lib/publishing/maven/publish-mvn.sh
test/expected.json
test/test-stack.ts

This allows publishing Maven artifacts to different repositories.
-----

feat(maven): allow configuring Maven endpoint

---

lib/publishing/nuget/publish.sh

For more info: https://docs.microsoft.com/en-us/nuget/create-packages/symbol-packages-snupkg
-----

fix(nuget): migrate to snupkg symbols package format

---

lib/publishing/nuget/publish.sh

chore: add warning if no .snupkg is found

---

lib/publishing/nuget/publish.sh

chore: don't attempt to push .snupkg twice

---

lib/chime-notifier/chime-notifier.ts
lib/chime-notifier/notifier-handler.ts
lib/pipeline.ts
test/chime-notifier.test.ts

More information == more better
-----

feat(chime): make the Chime notifier look up the failing action

---

lib/build-env.ts
test/expected.yml

feat: rename "env" to "environment" in BuildEnvironmentProps

---

lib/build-spec.ts
package.json

chore: remove unnecessary SDK dep

---

lib/auto-build.ts
lib/change-controller.ts
lib/chime-notifier/chime-notifier.ts
package.json
pipeline/delivlib.ts
test/bump.test.ts
test/canary.test.ts
test/chime-notifier.test.ts
test/expected.yml
test/open-pgp-key-pair.test.ts
test/pipeline.test.ts
test/shellable.test.ts
yarn.lock

chore: fixup after dependency updates

---

lib/pipeline-notifications/slack.ts

Ref: https://docs.aws.amazon.com/dtconsole/latest/userguide/concepts.html#detail-type
-----

feat(pipeline): control details from slack notifications

---

lib/registry-sync/ecr-mirror.ts
pipeline/delivlib.ts
test/registry-sync/ecr-mirror.test.ts

Adjusted the construct such that either schedule or autoStart is
configured. The construct is useless without either configured.
-----

chore: ecr mirror to run at 9AM everyday

---

lib/registry-sync/ecr-mirror.ts
test/registry-sync/ecr-mirror.test.ts

Repository names must be unique from mirror sources for a given
EcrMirror. Adding enforcement.
-----

fix(ecr-mirror): duplicate repository names get overwritten.

---

LICENSE

boilerplate content had not been updated.
-----

chore: update license information

---

lib/registry-sync/ecr-mirror.ts

fix: idempotencyToken is expected to be a string

---

lib/auto-build.ts
lib/repo.ts
test/auto-build.test.ts

Support selecting multiple branches for AutoBuilds.
-----

feat(autobuild): autobuild multiple branches

---

lib/pipeline-notifications/slack.ts

Ensure cross-stack references remain intact for the actual property
rendering, so that automated export/import behaves as intended.
-----

fix: only resolve slack config arns for hash calculation

---

lib/__tests__/publishing.test.ts
lib/pipeline.ts

feat: publishing steps can be put in separate stage

---

lib/__tests__/expected.yml
lib/auto-build.ts
lib/pull-request/pr.ts

Literally that. Add descriptions to all the CodeBuild projects we
create.
-----

feat: CodeBuild Project descriptions

---

lib/__tests__/expected.yml
lib/pull-request/bump.ts

Should have been in previous PR but I missed that this
feature lived in this library.
-----

chore: add default description to AutoBump

---

lib/pipeline.ts

feat: add the ability to add a manual approval action to a pipeline

---

.github/workflows/build.yml
.github/workflows/release.yml
.github/workflows/upgrade-main.yml
.projenrc.js
package.json

chore: update minNodeVersion to 14.17.0 to 14.18.0

---

lib/build-spec.ts
lib/shellable.ts

feat(shellable): add control over pipeline variables

---

lib/publishing/maven/publish-mvn.sh

fix: do not fail if JavaDocs are missing

---

README.md
lib/__tests__/expected.yml
lib/__tests__/package-integrity/integrity.test.ts
lib/__tests__/registry-sync/ecr-mirror.test.ts
lib/__tests__/registry-sync/mirror-source.test.ts
lib/__tests__/signing.test.ts
lib/__tests__/test-stack.ts
lib/build-env.ts
lib/publishing.ts
lib/registry-sync/ecr-mirror.ts
lib/signing.ts

Calling this a fix to ensure we release a new version of delivlib.
-----

fix: use bullseye superchain image

---

lib/publishing/golang/publish.sh

I typed the wrong script name.
-----

fix: GoLang publishing is broken
