cdklabs/aws-delivlib

README.md
lib/pipeline.ts
package.json
pipeline/delivlib.ts
test.sh
test/expected.json
test/pipeline.test.ts
test/run-test.sh

Our first unit test, to make it a habit to write
one for every feature.
Misc:
- Some updates to README
- Add "npm test synth" which outputs the template for inspection
- Clean up dashboard code that's not really useful (we can introduce later perhaps)

chore: unit test for `pipelineName`

---

lib/pipeline.ts
pipeline/delivlib.ts
test/test-stack.ts

If `notificationEmail` is set, send an SNS notification to the
specified email when any of the build/test/publish actions are failing.

feat(pipeline): send email notifications on any action failure

---

README.md
lib/publishing.ts
lib/publishing/docs/publish-docs.sh

to avoid bloating the gh-pages branch, the publisher
now will always force-push the contents of the site
with no git history.
Also, allow specifying a different branch name for
gh-pages.

feat(gh-pages-publisher): force-push without history

---

lib/pipeline.ts
lib/shellable.ts
lib/testable.ts
lib/util.ts
pipeline/delivlib.ts
test/expected.json
test/pipeline.test.ts
test/test-stack.ts

If `concurrency` is set to a number, no more than N actions will be run concurrently in the TEST and PUBLISH stages.
This allows overcoming the default account limitation of a 1 concurrency.

feat(pipeline): concurrency limit

---

lib/code-signing/certificate-signing-request.ts
lib/code-signing/certificate-signing-request/index.py
lib/code-signing/private-key.py
lib/code-signing/private-key.ts
lib/pgp-secret.ts
test/expected.json

The lambda code that back the Code Signing Certificate resources were
referencing the `logging` module using an incorrect name. This fixes the
incorrect naming, and adds descriptions to the Lambda functions (as well
as tagging a `purpose` on the entities that can be safely replaced).

fix: Logger reference in CSC custom resources

---

lib/pipeline.ts

(internal)
Exposes the failure alarm as a public property - we need this to configure our alarming actions internally.

Expose the failure alarm as a public property

---

lib/code-signing/code-signing-certificate.ts

Replace use of `cloudformation.ParameterResource` with `CfnParameter`,
so as to remove the deprecation warning that is emitted by JSII.

chore: Fix deprecated usage of cloudformation NS

---

lib/code-signing/certificate-signing-request.ts
lib/code-signing/code-signing-certificate.ts
lib/code-signing/private-key.ts
lib/credential-pair.ts
lib/pgp-secret.ts

The secrets VersionId field can be used to reference a particular instance of a secret
however this makes migrating secrets to a new location (by replacing the content with
a new value) impossible, and also doesn't work great with automatic secret rotation.
Hence, removing the option to even access it.
BREAKING CHANGE: The `privateKeySecretVersion` properties are no longer available,
instead, users are advised to resort to the `AWSCURRENT` staging label.

fix: Stop surfacing and using secret VersionIds

---

custom-resource-handlers/src/pgp-secret.ts
test/custom-resource-handlers/pgp-secret.test.ts

keys are created with a passphrase, and "with-signing-key.sh"
scripts expect a "Passphrase" field in the secret which should be
encoded as JSON. 
Not sure how this actually ever worked.

fix: pgp-secret did not store passphrase in secrets manager

---

lib/pgp-secret.ts
lib/signing-key.ts

The OpenPgpKey function remains available and simply proxies through to the PGPSecret instance
it is wrapping.

feat: Move permission grant function to PGPSecret

---

CHANGELOG.md
lib/pgp-secret.ts
package-lock.json
package.json
test/pgp-secret.test.ts

On `UPDATE`, the CustomResource needs to be able to re-read the private
key, so it is able to produce the public part of it again. This adds the
missing permission.

fix: Add missing permission to PGPSecret CustomResource

---

custom-resource-handlers/src/pgp-secret.ts
lib/open-pgp-key-pair.ts
test/custom-resource-handlers/pgp-secret.test.ts
test/expected.json
test/open-pgp-key-pair.test.ts

Since the grants on the SSM and SecretsManager API are tightened down to just the particular secrets/parameters being managed (given their names), the permission to "delete" the secret no longer exists when the resource is called if it no longer is in the stack (for the permission grant also is no longer in the stack).

fix: Don't attempt deleting OpenPGP keys' secrets

---

change-control-lambda/lib/time-window.ts
pipeline/delivlib.ts

Suspecting differences in how the milliseconds portion of parsed dates
get initialized when no milliseconds portion is provided in the parsed
string, attempting to zero out the milliseconds explicitly in an attempt
to fix breaking tests that I fail to reproduce locally.

chore: Neuter milliseconds of dates

---

lib/publishing.ts
lib/publishing/s3/publish.sh

S3 publisher can be made idempotent by giving it a unique token for
every version in a config file. Already-published revisions will not be
published again.
Switch to 's3 cp' instead of 's3 sync' to avoid reading the server-side
files; no need to do any syncing, we'll either do a full copy of all
files or no files.

feat(s3): make S3 publisher idempotent

---

superchain/Dockerfile

*Issue #79*
Modifies the Dockerfile for the superchain image to `pip install wheel`.

The Python language binding for JSII requires that wheel be installed.

---

lib/shellable.ts
test/shellable.test.ts

allow customizing failure alarm period, threshold and evaluation periods.
related: awslabs/cdk-ops#329

feat: shellable alarm configuration

---

lib/bump/bump.ts
package-lock.json

`standard-version` is intended to be run if you know there are changes
you want to release, and it will always do a version bump.
Put a `git` check in front of it which will abort early if there
have been no commits since the last release.

fix(autobump): stop AutoBump from releasing 0 changes

---

superchain/Dockerfile
superchain/README.md

Upgrading to .NET Core 2.2.202
I am keeping this as a draft until we get some mileage from our CDK PR builds to make sure it's all clear to upgrade.

feat: upgrade superchain to dotnet to 2.2.202

---

lib/publishing.ts
lib/publishing/npm/publish-npm.sh
test/test-stack.ts

When publishing to npm, you can now specify `distTag: 'TAG'`
and we will publish with `--tag=TAG`.

feat: support npm disttags

---

change-control-lambda/package-lock.json
change-control-lambda/package.json
change-control-lambda/test/handler.test.ts
lib/publishing/nuget/publish.sh
lib/publishing/nuget/sign.sh
package-lock.json
package.json
test/expected.json
test/run-test.sh
test/test-stack.ts

We cannot use mono's `signcode` tool until a release is available that
supports SHA256 signatures, so we'll be using osslsigncode in interim.
A patch has been submitted to mono to add support for SHA256 signatures
should be making it to a release "soon".
Related: mono/mono#11999
---
A previous iteration of this code was already see in awslabs/cdk-ops@844181b86893436661f75c4be12baf312d03a32a

chore(nuget-sign): Use osslsigncode for now

---

CHANGELOG.md
package-lock.json
package.json
test/expected.json

* **nuget-sign:** Use  osslsigncode for now ([#92](https://github.com/awslabs/aws-delivlib/pull/92)) ([e2855af](https://github.com/awslabs/aws-delivlib/commit/e2855af))

chore(release): v3.7.1

---

lib/build-spec.ts
lib/index.ts
lib/pipeline.ts
lib/publishing.ts
lib/publishing/github/publish.sh
lib/publishing/s3/publish.sh
lib/shellable.ts
lib/util.ts
package-lock.json
test/build-spec.test.ts
test/delivlib-tests/linux/void.sh
test/expected.json
test/pipeline.test.ts
test/test-stack.ts

Add multiple output artifact support for Shellable (including an initial
attempt at a BuildSpec helper as requested in awslabs/aws-cdk#2039).
Add multiple input artifact support for the GitHub publisher. The
tag and release notes will be taken from the primary artifact, the other
artifacts will be attached to the same release.
This is in preparation of publishing downloadable reference docs to
GitHub.

 feat: multiple artifacts for GitHub and Shellable 

---

lib/publishing.ts
lib/publishing/nuget/publish.sh
lib/publishing/nuget/sign.sh
test/expected.json

Now that Mono 6 is out we switched to the `jsii/superchain` image, which
uses this release, we are able to use `signcode` to issue `sha256`
signatures, instead of using un-maintained `osslsigncode`.
---

feat: use mono's signcode to sign .NET assemblies

---

lib/auto-build.ts
lib/bump/bump.ts
lib/pipeline.ts
lib/repo.ts
package-lock.json
package.json
pipeline/delivlib.ts
test/expected.json
test/pipeline.test.ts
test/test-stack.ts

If the `autoBuild` flag is set, a CodeBuild project
will be created and configured to automatically build
any commits to the repo, including GitHub pull requests.
If the `publicLogs` flag is also set, build logs will be published
to S3 and also a comment will automatically be posted on the GitHub
PR with a link.
Fixes #42

feat: auto-build (with public logs)

---

README.md

Added PyPi to Index
Updated KeyPair as `delivlib.SigningKey` appeared to have been removed from the delivlib.
-----

chore: minor updates

---

lib/auto-build.ts
lib/pipeline.ts
test/pipeline.test.ts

Allow a different buildspec to be specified for the AutoBuild project.
This enables PR builds to use a different buildspec file from the
CodeBuild project in the pipeline.
MOTIVATION
The aws-cdk package spends a significant amount of time (~20 minutes) in
the post-build step, where the build artifacts are packed. This, however, is
unnecessary for PR builds where the intention is to check if the build passes.
Specifying a separate buildspec.yml that has no post-build step will
speed up PR builds.
-----

feat: configure buildspec for AutoBuild project

---

lib/chime-notifier/chime-notifier.ts
lib/chime-notifier/notifier-handler.ts
lib/index.ts
pipeline/delivlib.ts
test/chime-notifier.test.ts

- The source was too big for inline code and so it didn't actually
deploy: strip out the source map.
- Move the configuration into the Lambda trigger's input (instead of
environment variables) so we can use a SingletonFunction for all
pipelines in the project.
- Add missing permissions to list the pipeline's actions.
- Fix the pattern
Add to Delivlib's own pipeline to properly test it.
-----

fix(chime): make Chime notifier actually deploy

---

lib/auto-build.ts
lib/repo.ts
test/expected.yml
test/pipeline.test.ts

The public build logs Serverless App retrieves the GitHub Token from the
CodeBuild project it's monitoring. For some reason (maybe because we
switched to Secrets Manager secrets) that token can't be retrieved
anymore and the posting would fail.
Also, the specific fields that the serverless app was reading have
been loudly deprecated according to the CodeBuild docs:
https://docs.aws.amazon.com/codebuild/latest/APIReference/API_ProjectSource.html#CodeBuild-Type-ProjectSource-auth
Update to a newer version of the serverless app in which this
token is an explicit parameter.
-----

fix: public build logs are broken

---

lib/auto-build.ts
lib/bump/bump.ts
lib/publishing.ts
lib/repo.ts
pipeline/delivlib.ts
test/bump.test.ts
test/expected.yml
test/test-stack.ts

Add support for automatically creating pull requests for bumps.
This requires the GitHub token to be available during bump. However, currently we model the GitHub token as a SecretValue, which resolves during deployment (by CloudFormation). This is not secure because it will pass the secret itself as environment variables. To address this, we changed `token` to `tokenSecretArn` and resolve it as needed (either during deployment if it’s required for a CFN definition or during runtime by extracting it from secrets manager).
BREAKING CHANGE: `repo.token` is now `tokenSecretArn` to enforce that the token is kept in AWS SecretsManager. Also, the API for `IRepo.createBuildSource` was modified.

feat(bump): create pull request for bumps

---

lib/shellable.ts
test/shellable.test.ts

Calls `grantRead` methods for secrets and SSM parameters passed as env
vars to shellable. Originally meant for consumers to handle on their end
but constructs don't necessarily expose the roles to be given access.
-----

fix: Grant env var access in shellable when needed

---

lib/pipeline.ts
test/expected.yml
test/pipeline.test.ts

Exposing the CodeBuild project in the pipeline will enable use cases
around creating monitoring resources. As an example, the build's
Duration and Failure metrics can be graphed on a CloudWatch dashboard.
Having a concrete name to the CodeBuild Project allows for the above
mentioned dashboards to reliably graph these across syntheses.
-----

chore(pipeline): configure name and expose build project

---

lib/pipeline.ts
test/expected.yml
test/pipeline.test.ts

This was accidentally introduced in a prior commit, which causes the
build project to depend on the pipeline for its name, while the pipeline
depends on the build project as part of its actions.
-----

fix(pipeline): cyclic dependency between CodePipeline::Pipeline and CodeBuild::Project

---

yarn.lock

Run `yarn upgrade` to get the latest minor and patch versions of
declared dependencies.
Resolves high severity vulnerability of minimist. Versions < 0.2.1 are
marked vulnerable.
https://github.com/awslabs/aws-delivlib/network/alert/yarn.lock/minimist/open
-----

chore: upgrade dependencies to latest

---

change-control-lambda/lib/time-window.ts
change-control-lambda/test/time-window.test.ts
test/expected.yml

This change implements this feature request: https://github.com/awslabs/aws-delivlib/issues/331
We use the ChangeController to enable and disable stage transitions in our pipeline based on a calendar of events. This works well when events are singular, however we'd also like to enforce change control on recurring events. For instance, we want to block stage transition into production waves after hours and on weekends.
Sample event for weekends:
```
BEGIN:VEVENT
RRULE:FREQ=WEEKLY;INTERVAL=1
DTEND:20200511T170000Z
SUMMARY:Outside of business hours (weekend)
DTSTAMP:20200504T163641Z
DTSTART:20200508T220000Z
SEQUENCE:0
END:VEVENT
```
-----

feat: recurring event support for change controller

---

lib/auto-build.ts
test/expected.yml

Delete previously published links to build logs before posting a new one
in the GitHub PR discussion. This avoids bloating PR comments which can
make review difficult.
See https://github.com/jlhood/github-codebuild-logs/pull/21 and
https://github.com/aws/aws-cdk/issues/5522.
-----

feat(auto-build): delete previous links to build logs

---

lib/shellable.ts

Useful when builds star to approach the default CodeBuild timeout of one hour.
-----

feat: allow setting a timeout for Shellable

---

lib/shellable.ts
test/expected.yml
test/shellable.test.ts

AWS STS deprecates the use of the global endpoint and all usage needs to be switched over to the regional endpoints.
As described in this issue: https://github.com/awslabs/aws-delivlib/issues/358, shellable's assumeRole Uses STS Global Endpoint.
This change resolves the issue using the environment variable `AWS_STS_REGIONAL_ENDPOINTS`. 
The default behavior will remain the same as `AWS_STS_REGIONAL_ENDPOINTS` will be set to value `legacy` and the calls will still go to the global endpoint. Although now we expose the boolean flag `useRegionalSTSEndpoints` and if it's set to `true`, then `AWS_STS_REGIONAL_ENDPOINTS=regional` will be used and the calls will go to the regional endpoints.
-----
By submitting this pull request, I confirm that my contribution is made under the terms of the …

feature: expose STS endpoint type

---

.github/workflows/auto-merge-prs.yml
lib/code-signing/code-signing-certificate.ts
test/code-signing-cert.test.ts

The RSA key name used to be calculated off of the signing cert's
complete construct path.
This requires it to be replaced if the construct tree is refactored
(and specifically, if the location of the containing stack is moved,
such as it being moved into a `Stage`).
A name that is based off of the stack's deployment name and the
construct path *inside* the stack:
* is indifferent to the stack's location in the construct tree.
* is backwards compatible with simple setups.
For non-backwards compatible cases, the name is now also configurable.
-----

fix: make changes to RSA key construct path backwards compatible 

---

lib/publishing.ts
lib/publishing/npm/publish-npm.sh
test/test-stack.ts

Default to access=public so we don't change existing behavior.
resolves https://github.com/awslabs/aws-delivlib/issues/368
-----

npm --access=restricted now supported

---

lib/pull-request/pr.ts
test/bump.test.ts

Updated the autoPR code that clones the repo if needed to work with repos that do not have a branch named master.
This resolves the issue https://github.com/awslabs/aws-delivlib/issues/450 and fixes AutoMergeBack MR's for repos that do not have a master branch.
-----

fix(pr): AutoPR handle repos without master branch

---

pipeline/delivlib.ts

This is due to our switch to the `main` branch instead of `master`.
-----

fix: auto bump does not work for delivlib's own pipeline

---

README.md
lib/chime-notifier/chime-notifier.ts
lib/index.ts
lib/pipeline-notifications/chime.ts
lib/pipeline-notifications/index.ts
lib/pipeline-notifications/slack.ts
lib/pipeline.ts
test/expected.yml
test/pipeline-notifications/chime.test.ts
test/pipeline-notifications/slack.test.ts
test/pipeline.test.ts

The pipeline notifications is now switched to use a bind pattern
with an enum-like class for better APIs.
This makes the API extensible with the ability for users to write
their own if they wish. It also makes the interface cleaner and
reduces property fragmentation on `PipelineProps` for the same
feature, i.e., failure notifications.
BREAKING CHANGES: The property `failureNotifySlack` has been
removed and replaced by `notifyOnFailure()` API.
-----

chore(pipeline): refactor failure notification to use bind pattern

---

lib/auto-build.ts
lib/pipeline.ts
package.json
test/pipeline.test.ts
test/test-stack.ts

This PR exposes the underlying `CodeBuild` project created by:
- The `AutoBuild` construct
- The `Shellable` construct
We need this in order to grant various permissions to the project roles.
BREAKING CHANGE: `pipeline.addShellable` now returns the shellable in addition to the action. Use `.action` to retrieve the action 
-----

feat: expose underlying codebuild projects

---

lib/change-controller.ts
lib/publishing/nuget/publish.sh
lib/publishing/pypi/publish.sh
lib/shellable.ts
test/canary.test.ts
test/expected.yml

As part of investigating how to test publishing of V2, I discovered that neither
the Nuget or PyPI publishing scripts appear to handle the FOR_REAL env variable
that is respected by the other publishing steps. Copying the patterns from the
other publishing steps so these steps can be tested/mocked as well.
Related changes:
* I had to update the CodeBuild images, as the existing ones were deprecated and couldn't be used to launch new projects.
-----

chore: make Nuget and PyPI publishing respect the FOR_REAL variable

---

README.md
lib/index.ts

Previously, AutoBuild was only available via the Pipeline construct.
This change exports the AutoBuild construct so it can be used without
needing to create a Pipeline.
-----

feat: AutoBuild as its own feature

---

lib/pipeline-notifications/slack.ts
test/pipeline-notifications/slack.test.ts

The `Name` property of `AWS::CodestarNotifications::NotificationRule`
needs to be unique within the account and region.
If it is not unique, then resource replacement will fail.
Include the hash in the `Name` property so as to keep it unique.
-----

fix(pipeline-notifications): deployment fails to replace codestar notifications resource

---

lib/chime-notifier/chime-notifier.ts
test/chime-notifier.test.ts

The cause is that the webhook url gets added as an id to the construct.
Change the logic so that the chime notifier construct path is used to
make the id unique instead.
-----

fix(chime-notifier): synthesis fails when webhook url is a token

---

lib/registry-sync/ecr-mirror.ts
lib/registry-sync/mirror-source.ts
test/registry-sync/mirror-source.test.ts

The CodeBuild sync job needs to have permissions to read the S3 bucket
where the mirror source places the source files.
-----

fix(ecr-mirror): sync job fails when using MirrorSource.fromDirectory()

---

lib/auto-build.ts
test/expected.yml
test/pipeline.test.ts

Removes noise in PR comments.
I bet those logs are hardly ever checked.
See https://github.com/jlhood/github-codebuild-logs/pull/29
-----

feat(auto-build): option to not publish build logs when build is successful

---

lib/pipeline.ts
lib/pull-request/bump.ts
lib/pull-request/merge-back.ts
lib/pull-request/pr.ts

We've introduced an Omit chain in the interfaces around auto pull 
requests. Instead, use more traditional 'Props inherits Options'
approach to make the code more readable.
----
Applied this with change on `cdk-ops` using `yarn link` and noted that there were no visible changes that seemed to indicate a diff here. 
-----

chore(pull-request): remove the use of Omit chain

---

lib/pull-request/bump.ts
lib/pull-request/merge-back.ts
lib/pull-request/pr.ts

The refactoring in #671 unintentionally changed the signature of
AutoMergeBackOptions to make `repo` a required property, and also
added the `stage` property to AutoMergeBackProperties. This change
reverts both back to the pre-refactor state.
-----

fix: remove repo as required property of AutoMergeBackOptions

---

lib/pipeline.ts
lib/pull-request/merge-back.ts

As discussed in #684, refactoring the AutoMergeBack interfaces to have a more
standard hierarchy. This change removes 'stage' from AutoMergeBackOptions,
and creates a stage-specific AutoMergeBackPipelineOptions.
BREAKING CHANGE: the 'stage' prop of AutoMergeBackOptions has been moved to a
new AutoMergeBackPipelineOptions interface.
-----

chore(bump): refactor AutoMergeBackOptions

---

README.md
lib/pipeline-watcher/handler/watcher-handler.ts
lib/pipeline-watcher/watcher-handler.ts
lib/pipeline-watcher/watcher.ts
lib/pipeline.ts
package.json
test/expected.yml
test/watcher-handler.test.ts
test/watcher.test.ts
yarn.lock

Currently, metrics are emitted for each pipeline failure as
`<pipelineName>_FailedStages`. This metric is emitted per pipeline once
per minute depending on the state of the pipeline at the time.
This means that if a pipeline is in failed state for 20 minutes, there
will be 20 non-zero datapoints for this metric.
This is not very useful in aggregating failure over time and summarizing
them over hours, days or weeks.
This commit changes the approach entirely. Instead of running the
metrics on a fixed schedule, it reacts to CodePipeline events and emits
the appropriate metric. This should result in one non-zero data point
per failure.
This commit also changes the metric name and includes dimensions for
better querying. It now emits a single metric `PipelineActionFailures`
under the namespace …

feat(pipeline): improved pipeline failure metrics

---

lib/publishing/pypi/publish.sh
test/expected.yml

`twince`, which is used by the python publisher, has a dependency on the `cryptography` module.
As described in their [changelog], starting version 3.4, they require the latest version of `pip`. Otherwise,
the installer will attempt to compile the module, and the Rust compiler will be required.
This fails in the amazon/aws-sam-cli-build-image-python3.6 image since it has an older version of pip installed.
To fix, simply add an instruction to the dockerfile to upgrade to the latest pip version before installing.
[changelog]: https://cryptography.io/en/3.4/changelog.html#v3-4
-----

fix(pypi): cryptography >= 3.4 is not supported by older pip

---

lib/pipeline.ts
lib/publishing.ts
lib/publishing/golang/publish.sh
lib/shellable.ts
lib/util.ts
test/expected.yml
test/shellable.test.ts
test/test-stack.ts

Add support for publishing golang code from the build artifact (under the `go/` directory) to a GitHub repository.
To add a go publishing step to your pipeline, use `pipeline.publishToGolang()` or create an instance of `PublishToGolang` construct.
See the README of [jsii-release] for more details.
**MISC**: allow `Shellable` environment values to be `undefined`, and then they will not be set.
**TESTING**: updated [awslabs/aws-delivlib-sample](https://github.com/awslabs/aws-delivlib-sample) to include a `go` section in the jsii config and tested that the delivlib test pipeline publishes go bindings to the same repo (under the [golang](https://github.com/awslabs/aws-delivlib-sample/tree/golang) branch).
Resolves aws/jsii#2562
[jsii-release]: https://github.com/aws/jsii-release
-----
By …

feat: golang publishing

---

lib/registry-sync/ecr-mirror.ts
test/registry-sync/ecr-mirror.test.ts

Otherwise, all stack `Export`s change, which is not possible.
-----

fix(ecr-mirror): only represent non-`latest` tags in construct IDs

---

.gitignore
package.json
test/expected.yml
yarn.lock

The CDK CLI can be at any version greater than the CDK framework. So use
a caret dependency on this.
Motivation
Move to the latest CDK CLI that depends on netmask@2 (netmask@1 has a
known security vulnerability)
-----

chore: caret dependency on the CDK CLI

---

README.md
lib/shellable.ts
package.json
pipeline/delivlib.ts

Updates required to migrate to the new `cdklabs` GitHub organization
-----

chore: migrate to cdklabs

---

lib/registry-sync/ecr-mirror.ts
lib/registry-sync/mirror-source.ts
test/registry-sync/ecr-mirror.test.ts

The previous implementation for "mirror multiple tags from the same
repository" was broken: it tried to create a repository per repo×tag,
instead of simply creating a repository per repository and mirroring
all the desired tags inside.
A subsequent problem would be that the construct identifiers of the
two sister repos would conflict, and cause problems in our ops codebase
where the repos are created in a separate stack (and hence lead to
Export rename trouble).
Simplify by doing a repo-per-repo and mirroring multiple tags inside
that repo.
This change is necessary to unblock `delivlib` progress inside cdk-ops.
-----

fix: reuse same repository for multiple tags

---

lib/registry-sync/mirror-source.ts
test/registry-sync/mirror-source.test.ts

Allow build time variables, aka build-arg, to be configured when the
docker image is being built from a local directory.
-----

feat(registry-sync): docker build time variables

---

lib/pipeline.ts
lib/util.ts
test/pipeline.test.ts

This extends the new pipeline failure metric approach introduced in #696,
by adding convenience methods to expose pipeline failure metrics at the per-
action level.
-----

feat(pipeline): improved pipeline action failure metrics

---

README.md

The projen migration [PR](https://github.com/cdklabs/aws-delivlib/pull/841) introduced a breaking change.
Unfortunately when I merged the PR manually I removed the breaking change notice by accident.
This is just a dummy PR to re-introduce the notice so that `standard-version` performs a major version bump when the next release happens.
BREAKING CHANGE: `esbuild` or `docker` is required in order to bundle the change-control-lambda
-----

chore: change-control-lambda migrated to `NodeJsFunction`

---

lib/__tests__/run-test.sh

When integration test expected files get out of date, the command in the error message should work to run the integration tests. 
-----

chore(integ tests): update message with integ test update command

---

package.json

projen publishing (see #1033) uses GitHub releases/tags to track versions, and
doesn't use the version in package.json. The release is currently failing
because this version is still being set here.
-----

chore: set package.json version to 0.0.0

---

.github/workflows/release.yml
.projen/tasks.json
.projenrc.js
package.json
package.sh

The `release` and `bump` tasks write to `dist/changelog.md` and
`dist/version.txt`. Unfortunately, the `publish.sh` script that delivlib
uses removes the `dist` directory before copying over the artifacts. This caused
the release to fail.
Also, explicitly enable publishing to npm
-----

chore: fix package.sh for publishing

---

lib/__tests__/expected.yml
lib/publishing/nuget/publish.sh

The new superchain images are based on debian, so we cannot use yum to
install openssl and jq. Detect whether yum or apt-get is installed, and
issue the correct commands. Display a warning if neither of the tools is
found.
-----

feat: make NuGet publisher support yum AND apt-based distributions

---

lib/__tests__/expected.yml
lib/publishing.ts
lib/publishing/github/create-release.js

Currently, the GitHub publishing job looks for a CHANGELOG file (either in a
default location or set by environment variable), parses the changelog for the
current version, and uses that result as the release notes. This change enables
an alternative approach; creating a RELEASE_NOTES file which contains the
complete release notes, ready for publishing.
The advantage of this new approach might be if you want to do some
post-processing formatting on the changelog (or even include extra notes not
normally present in the default changelog). For CDKv2, this will be used to
combine the changelog entries for the stable release (aws-cdk-lib) and for the
alpha modules.
related https://github.com/aws/aws-cdk/issues/16802
-----
By submitting this pull request, I confirm that my contribution is made …

feat: support release notes for GitHub publishing

---

package.json
yarn.lock

chore(deps): upgrade jest dependency due to CVE-2021-23440

---

lib/publishing/s3/publish.sh

The S3 publisher uses a signaling file in the target bucket to show
that a particular release has already been uploaded, and it should
skip uploading any of the files in the current distribution.
However, it used `aws s3 ls` to do that, which matches prefixes.
So if we previously uploaded `xyz-1.2.3-pre`, and are now trying to
upload `xyz-1.2.3`, it will incorrectly skip the new upload.
Switch to using `aws s3 cp` to fix this.
-----

fix(s3): S3 publisher incorrectly skips prefix releases

---

.github/workflows/auto-approve.yml
.projenrc.js

I think we just didn't change this from when before we had the `cdklabs-automation` user, which is the one creating the upgrade PR's.
-----

chore: wrong auto approve username

---

lib/__tests__/expected.yml
lib/build-env.ts

The 'latest' tag has been discontinued for the jsii/superchain image (documented [here](https://hub.docker.com/r/jsii/superchain)). This change updates the default image from 'latest' to the recommended replacement, '1-buster-slim'
Closes #1114 
-----

fix(defaults): Change default image to reflect new jsii image tags

---

.projen/tasks.json
.projenrc.js
README.md
lib/__tests__/expected.yml
lib/__tests__/package-integrity/integrity.test.ts
lib/__tests__/registry-sync/ecr-mirror.test.ts
lib/change-controller.ts
lib/chime-notifier/chime-notifier.ts
lib/code-signing/certificate-signing-request.ts
lib/code-signing/private-key.ts
lib/open-pgp-key-pair.ts
lib/pipeline-watcher/watcher.ts
lib/publishing.ts
lib/registry-sync/ecr-mirror.ts

The default (`latest`) tag was being used, but it no longer exists.
Replaces it with the `1-buster-slim` tag which is the recommended
substitute.
Also, upgrades to Node 14.x where Node 12.x was still being used.
-----

fix: ECR mirrorring uses incorrect jsii/superchain tag

---

.projen/deps.json
.projen/tasks.json
package.json
yarn.lock

Manually bump projen because the automatic dependency upgrades [PR](https://github.com/cdklabs/aws-delivlib/pull/1134) has been failing for a while (we are on it).
This is needed because the new version of projen contains a [fix](https://github.com/projen/projen/pull/1947) to jest issue currently failing our unit tests.
-----

chore(deps): upgrade projen

---

lib/__tests__/change-control-lambda/time-window.test.ts
lib/__tests__/registry-sync/ecr-mirror.test.ts
lib/__tests__/registry-sync/mirror-source.test.ts
lib/registry-sync/ecr-mirror.ts
lib/registry-sync/mirror-source.ts

This affords an increased rate limit for pulls. Additionally, switch to using the `public.ecr.aws/jsii/superchain` image instead of pulling it from DockerHub, and clarify the MirrorImage doesn't need to come from DockerBug by introducing an alternate (and improved) static factory.
In orde to enable reducing the scope of changes incurred by migrating from DockerHub images to using their equivalent ECR-Public URL, allows configuring a custom ECR Repository name to be used on the output side.
-----

chore: authenticate ECRMirror to ECR Public

---

lib/__tests__/expected.yml
lib/__tests__/test-stack.ts
lib/code-signing/code-signing-certificate.ts
lib/publishing.ts

The prefix `jsii` is now available.
-----

chore: switch the test pipeline image to public.ecr.aws/jsii/superchain:1-buster-slim-node18

---

lib/shellable.ts

Forgot to pass the property to the right function.
-----

fix(shellable): passing args was broken

---

.github/workflows/build.yml
.github/workflows/release.yml
.github/workflows/upgrade-main.yml
.projen/deps.json
.projenrc.js
lib/__tests__/canary.test.ts
lib/__tests__/package-integrity/handler/integrity.test.ts
lib/__tests__/registry-sync/ecr-mirror.test.ts
lib/registry-sync/ecr-mirror.ts
package.json
yarn.lock

Switching back to dockerhub as the codebuild source image since it is not possible to use an ECR public image.
-----

chore: switch back to dockerhub image

---

lib/publishing/maven/publish-mvn.sh

Revert #1329 because it didn't work.
Try a new way of fixing the error, using this as reference: https://stackoverflow.com/questions/70153962/nexus-staging-maven-plugin-maven-deploy-failed-an-api-incompatibility-was-enco
-----

chore: add maven options to patch upstream dependencies of nexus-staging-maven-plugin

---

lib/__tests__/canary.test.ts
lib/__tests__/registry-sync/ecr-mirror.test.ts
lib/auto-build.ts
lib/build-env.ts
lib/pipeline.ts
lib/publishing.ts
lib/pull-request/pr.ts
lib/registry-sync/ecr-mirror.ts
lib/registry-sync/mirror-source.ts
lib/shellable.ts
package.json
yarn.lock

Change default CodeBuild image to `aws/codebuild/standard:7.0` which has node18. This version does not ship with yarn, so we
add a check to conditionally install yarn if not present.
Upgrades version of jsii/superchain to a supported one. Also switch over to use the public ECR for superchain images. Gives all projects the required permissions to pull from the public ECR.
-----

feat: support node18 & default to node18

---

lib/__tests__/registry-sync/ecr-mirror.test.ts
lib/registry-sync/ecr-mirror.ts

The build image was changed to use jsii/superchain from the Public Amazon ECR, but this doesn't work when `RegistryCredential` is configured. This behavior is documented (https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-codebuild-project-environment.html#cfn-codebuild-project-environment-registrycredential)
-----

fix: ecr-mirror code build fails to start

---

lib/__tests__/signing.test.ts
lib/shellable.ts
lib/signing.ts

This PR exposes the underlying `role` property used to specify a role to be used by the CodeBuild project created as part of creating a new `Shellable`
-----

feat: expose service role to allow custom codebuild role for shellables

---

lib/__tests__/signing.test.ts
lib/signing.ts
lib/signing/nuget/sign.sh

This PR adds properties on the `SignNuGetWithSignerProps` interface that allow a user to specify the profile and owner that will be used for signing. These properties are added as environment variables that are passed in the payload to the signing lambda as part of the`sign.sh` script. The signing lambda can utilize these values to start the signing job with the specified signer profile and owner. In addition to the above changes, `sign.sh` has been updated to provided the entire path of the dll file to upload to the signing bucket. This fixes an error where the --body value must be a full path.
-----

feat: add props on `SignNuGetWithSignerProps` for signer profile and signer owner

---

.github/workflows/build.yml
.github/workflows/release.yml
.github/workflows/upgrade-main.yml
.projen/deps.json
.projenrc.ts
package.json
yarn.lock

chore: upgrade minNodeVersion to 18+

---

lib/custom-resource-handlers/src/_rmrf.ts

When the GPG agent is shutdown, it removes some UNIX sockets from the temporary directory. Their removal may race with the `rmrf` that we run in the custom resource, leading to an `ENOENT` error.
Catch it and continue. Ultimately, this code runs in a Lambda and all files are going to disappear anyway.
-----

fix(gpg resource): survive errors during cleanup

---

lib/publishing/maven/publish-mvn.sh

Maven staging often takes longer than the default 5 minutes. Increase to 10.
Currently we are seeing the following error:
```console
Waiting for operation to complete...
....................................................................................................
[WARNING] TIMEOUT after 302.4 s
[ERROR] Rule failure while trying to close staging repository with ID "softwareamazon-7956".
[ERROR] 
[ERROR] Nexus Staging Rules Failure Report
[ERROR] ==================================
[ERROR] 
[ERROR] 
[ERROR] Cleaning up local stage directory after a Rule failure during close of staging repositories: []
[ERROR]  * Deleting context 4714fd1f794.properties
[ERROR] Cleaning up remote stage repositories after a Rule failure during close of staging repositories: []
[ERROR]  * Dropping failed …
```

fix: maven staging timeout

---

lib/publishing.ts

chore: use bookworm-slim-node20 jsii-suprchain image in publishing.ts

---

lib/publishing/nuget/publish.sh

When the NuGet publishing script assumes a role to retrieve the API key secret, it pollutes the global environment variables with the role credentials.
When we then later try to write to SSM, it uses the wrong role (the secret role instead of the CodeBuild role).
Retrieve the secret credentials in a subshell so they don't interfere with the CodeBuild credentials.
-----

fix: NuGet job can't write to SSM when using secret role

---

lib/__tests__/package-integrity/integrity.test.ts
lib/package-integrity/handler/integrity.ts
lib/package-integrity/integrity.ts

Some builds will require env vars set to run a build correctly or authenticate with upstream services. Allow passing through all types of CodeBuild env vars to the underlying Shellable job.
-----

feat(package-integrity): can pass env vars to integrity build

---

.projen/deps.json
.projenrc.ts
lib/registry-sync/mirror-source.ts
package.json
yarn.lock

In the CDK Pipeline, we call `fromDir()` with an absolute path and that path makes its way into the construct ID.
Because in a pipeline the current working directory contains an arbitrary string, the construt ID will be different every run.
This construct ID makes its way into the asset display name, and the asset display name makes its way into the Pipeline, which will be updated on every run and restart on every run.
Give a fixed display name so this doesn't happen anymore. It may not be unique, but that is not necessary for display names.
-----

fix: MirrorSource.fromDir() leads to a looping self-mutation
